### ISSUE TITLE
crafting incompatibility

### ISSUE THREAD

**Issue by GabrielitoPL** [asylumdevgroup/Omega-1#2]
Good morning friend, I'm playing your pack recently and I have a problem with the crafting compatibility, I was trying to craft a RE-Battery from the industrialcraft classic, but the tech reborn battery appears, I thought it was because of the copper cable, but I try to craft from Industrialcraft and I only get from tech reborn, I don't know if I'm wrong or there is a problem, if there will be a solution, that's all.

version modpack ADG Omega 1-4.1.8
Minecraft 1.12.2
![Desktop 17-12-2020 10-59-42-71](https://user-images.githubusercontent.com/25838463/102512624-41319400-4058-11eb-9e36-b65170ebcc3d.png)
![Desktop 17-12-2020 11-00-16-3](https://user-images.githubusercontent.com/25838463/102512634-41ca2a80-4058-11eb-86e2-bb107a188cd7.png)
![Desktop 17-12-2020 11-01-21-175](https://user-images.githubusercontent.com/25838463/102512637-4262c100-4058-11eb-9f26-9d62a0d4fe1a.png)

**Comment by mcadventurecity** [comment]
Thank you for reporting, I will look into this for the next update.

**Comment by GabrielitoPL** [comment]
Very good colleagues who have a good start to the year, anyway, I wanted to ask myself if when the new update that corrects this error arrives, will I be able to continue playing my world or do I have to create another to avoid any problems?

**Comment by mcadventurecity** [comment]
I have decided to swap out IC2 Classic and use Normal IC2 with classic mode enabled in the config (Thanks @CrankySupertoon for bringing that to my awareness). This enables near-identical functionality while maintaining compatibility with Tech Reborn.

**Comment by furtabs** [comment]
> I have decided to swap out IC2 Classic and use Normal IC2 with classic mode enabled in the config (Thanks @CrankySupertoon for bringing that to my awareness). This enables near-identical functionality while maintaining compatibility with Tech Reborn.

It’s also world breaking so make it super clear in the changelog
