### ISSUE TITLE
Integrate forestry

### ISSUE THREAD

**Issue by GabrielitoPL** [asylumdevgroup/Omega-1#3]
Good, I would like it to be integrated in the modpack ADG Omega 1 the forestry, due to the issue of bees and forest machines to have more of the industrial environment, I would appreciate it very much and that you pending that crafting incopativility when adding this mod if thank you very much. :3

**Comment by mcadventurecity** [comment]
We had Forestry a long time ago, but removed it due to RAM usage issues.
