### ISSUE TITLE
Advanced machine classic asks

### ISSUE THREAD

**Issue by GabrielitoPL** [asylumdevgroup/Omega-1#4]
Well everyone, excuse me for the inconvenience, could you help me with an error, I have the IC2 with the classic profile, but when installing advanced machines it also hangs me in this mod, I have to change the profile? If so, can you help me or did I miss something?
Version 1.12.2
modpack 4.2.0

**Comment by mcadventurecity** [comment]
You have to also install a patcher mod for Advanced Machines to Work. https://www.curseforge.com/minecraft/mc-mods/advanced-machines-patcher
